### ISSUE TITLE
TypeError: unsupported type for timedelta seconds component: NoneType

### ISSUE THREAD

**Issue by ladiko** [pc-coholic/eSSP#10]
Whenever I call sync(), i get this:
```

Traceback (most recent call last):
  File "./cc_ssp.py", line 11, in <module>
    k.sync()
  File "/home/user/eSSP.py", line 289, in sync
    result = self.send([self.getseq(), '0x1', '0x11'])
  File "/home/user/eSSP.py", line 402, in send
    response = self.read(process)
  File "/home/user/eSSP.py", line 410, in read
    timeout_expired = datetime.datetime.now() + datetime.timedelta(seconds=self.timeout)
TypeError: unsupported type for timedelta seconds component: NoneType
```

It was introduced in this commit: https://github.com/pc-coholic/eSSP/commit/8d3bedaa7a9dd196d0ef8735ae6d22177a49df3b

The version before, is working for me.

**Comment by pc-coholic** [comment]
I think I know why this is happening - I'll take a look at it as soon as possible..

However that may take some time, as I don't have access to a device to test it at the moment.
